<?php

declare(strict_types=1);

namespace App\Providers;

// use Illuminate\Support\Facades\Gate;
use App\Models\Agreement;
use App\Models\Post;
use App\Models\Rate;
use App\Models\Selective;
use App\Models\User;
use App\Policies\AgreementPolicy;
use App\Policies\PostPolicy;
use App\Policies\RatePolicy;
use App\Policies\SelectivePolicy;
use App\Policies\UserPolicy;
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;

class AuthServiceProvider extends ServiceProvider
{
    /**
     * The model to policy mappings for the application.
     *
     * @var array<class-string, class-string>
     */
    protected $policies = [
        User::class => UserPolicy::class,
        Agreement::class => AgreementPolicy::class,
        Rate::class => RatePolicy::class,
        Selective::class => SelectivePolicy::class,
        Post::class => PostPolicy::class,
    ];

    /**
     * Register any authentication / authorization services.
     */
    public function boot(): void
    {
        $this->registerPolicies();
    }
public function registerPolicies()
{
    parent::registerPolicies(); // TODO: Change the autogenerated stub
}
}
